# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Blog"
#email: yoshua.elmaryono@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Insert blog description.
#baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dotm.github.io" # the base hostname & protocol for your site
contacturl: "/contact"
blogurl: "/blog"
#twitter_username: jekyllrb
github_username: dotm

exclude:
- book.md

# Build settings
markdown: kramdown

#plugins
plugins:
  - kramdown